blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/directus/directus/discussions/new
    about: Share your ideas on how to make Directus better.
  - name: Directus Community Support
    url: https://directus.chat/
    about: Please ask and answer questions here.
